### ISSUE TITLE
beam PA unit mismatch when making the convolution kernel in convolve_with_beam()

### ISSUE THREAD

**Issue by leontrapman** [richteague/gofish#11]
Hi @richteague,

I found an issue with the PA of the beam that is used when convolving the keplerian mask. In ```convolve_with_beam()``` the beam PA (in degrees) is passed along to ```astropy.convolution.Gaussian2DKernel```, which expects a rotation angle in radians (at least in astropy 5.1.1: https://docs.astropy.org/en/stable/api/astropy.convolution.Gaussian2DKernel.html). 
I fixed it by replacing ```theta=self.bpa``` with ```theta=np.deg2rad(self.bpa)``` , but any similar conversion would do the trick.

Cheers,
Leon

**Comment by richteague** [comment]
Thanks, @leontrapman! I've pushed this change.
