### ISSUE TITLE
Integrated spectrum after shifting/ stacking the cube

### ISSUE THREAD

**Issue by MargotLeemker** [richteague/gofish#14]
Hi Rich,

There is a difference in the integrated spectra for stacked cubes made with gofish and Carta. This difference is only visible in cubes with a bright emitting line at the edge of the spw (e.g., for line-rich sources). 

This difference can be seen when comparing the following spectra:
1. Stacked cube by gofish —> load in Carta —> extract a ‘flux density’ spectrum.
2. Not-stacked cube —> load in gofish —> make an integrated_spectrum specifying Mstar etc to stack the spectrum.

These 2 spectra are very similar for all velocities except for the first and last channels due to the way the spectrum is calculated. For spectrum 1, Carta integrates all pixel values but for spectrum 2, the integrated flux is calculated through the average flux * emitting area. In the case of bright lines in the channels at the edge of the spw this makes a difference as half of the pixels are NaN so the average spectrum is equal to the average of all the non-NaN pixels. But for the emitting area, all pixels are included. This causes the difference between the spectra. 

Best,
Margot

**Comment by richteague** [comment]
Can you try with the new version 1.6.11 and see if that solves the issue?
