### ISSUE TITLE
unnecessary reading of fits header value CRVAL in _readpositionaxis

### ISSUE THREAD

**Issue by gica3618** [richteague/gofish#5]
In the function _readpositionaxis, the variable a_ref is assigned the value of the crval from the fits header, but in the next line, a_ref is assigned to 0. So reading crval from the header seems unnecessary.

**Comment by richteague** [comment]
Yes, that's right. I think this was vestigial code from when I was toying with having absolute (RA, dec) axes but found that simple offsets were more reliable when dealing with the different types of headers from different RT codes.
